spring:
  datasource:
    url: jdbc:mysql://qin.qins.online:3306/petShop
    username: root
    password: root@@@###
    driver-class-name: com.mysql.cj.jdbc.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration # ??Spring Security
  web:
    resources:
      static-locations: "file:///E:/tempstatic/"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
upload:
  file:
    location: "file:///E:/tempstatic/"
    path: /static/**

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      table-prefix: ms_

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9090
#  jpa:
#    hibernate:
#      ddl-auto: update

